site_name: MLCommons Science Working Group AI Benchmarks Collection
site_url: https://mlcommons-science.github.io/benchmarks
repo_url: https://github.com/mlcommons-science/benchmark/
repo_name: MLCommons Science Benchmarks
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.share
    - navigation.search.suggest
    - navigation.search.expand
    - navigation.search.autocomplete
nav:
  - index.md
  - Report: benchmarks.pdf
  - Benchmarks: md/benchmarks/index.md