site_name: MLCommons Science Working Group AI Benchmarks Collection
site_url: https://mlcommons-science.github.io/benchmarks
repo_url: https://github.com/mlcommons-science/benchmark/
repo_name: MLCommons Science Benchmarks

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.share
    - navigation.search.suggest
    - navigation.search.expand
    - content.code.copy
    - content.tabs.link

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/filters.js

# enable niceties used by the cleaner layout
markdown_extensions:
  - pymdownx.superfences

nav:
  - index.md
  - Report: benchmarks.pdf
  - Benchmarks: md/benchmarks/index.md
