site_name: Gregors Sample Site
theme:
  name: material  # You can switch to 'mkdocs' if you don’t want Material
nav:
  - Home: index.md
  - Table: table.md
  - Benchmark: benchmark.md

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js
  - https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js
  - https://cdn.datatables.net/buttons/2.4.1/js/buttons.colVis.min.js
  - js/table.js

extra_css:
  - https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css
  - https://cdn.datatables.net/buttons/2.4.1/css/buttons.dataTables.min.css
  - css/extra.css

markdown_extensions:
  - attr_list
  - md_in_html